### ISSUE TITLE
Typo in Package module name (dcmje)

### ISSUE THREAD

**Issue by swederik** [dcmjs-org/dcmjs#108]
https://github.com/dcmjs-org/dcmjs/blob/a614cac04efec0cb42de4d99ed258e98d015e4fc/package.json#L6

**Comment by pieper** [comment]
Any reason not to just edit it in place?

**Comment by dannyrb** [comment]
The field is only used if you're using a bundler, and that file path resolves. If that's not the case, then it falls back to main.

Perfectly okay to edit in place. I'll do that now.
