### ISSUE TITLE
Should I add ArrowAnnotate into index.js?

### ISSUE THREAD

**Issue by jenhaoyang** [dcmjs-org/dcmjs#131]
I see dcmjs already have ArrowAnnotate.js, is ArrowAnnotate ready to use?
https://github.com/dcmjs-org/dcmjs/blob/0e1e2921e953bde8f4707b025f584a6c558ffedd/src/adapters/Cornerstone/index.js#L9-L16

**Comment by JamesAPetts** [comment]
Hey, I also just noticed this, its not exposed here if you need the class: https://github.com/dcmjs-org/dcmjs/pull/132
