### ISSUE TITLE
Implement Adapter of Cornerstone Rectangle Annotation 

### ISSUE THREAD

**Issue by jenhaoyang** [dcmjs-org/dcmjs#137]
I am new to DICOM and I need some guide.
I want to Implement rectangle annotation by following the pattern of EllipticalRoi.js in 

dcmjs/src/adapters/Cornerstone/EllipticalRoi.js.

Is there any related resource will help to Implement Rectangle Annotation or the imformation in the EllipticalRoi.js is enough?

**Comment by pieper** [comment]
yes, I think that would make sense.  @JamesAPetts has been working on that and may have suggestions.

Refer to this document for guidance:

https://docs.google.com/document/d/1bR6m7foTCzofoZKeIRN5YreBrkjgMcBfNA7r9wXEGR4/edit#heading=h.zfhnzramjbpv

**Comment by jenhaoyang** [comment]
@JamesAPetts  I saw these implement hints from dcmjs/src/utilities/TID300/index.js. But I am not clear about those hint, could you explain more detail? 
Is that are the Hierarchy I need to implement in dcmjs/src/utilities/TID300/Rectangle.js like dcmjs/src/utilities/TID300/Ellipse.js do?
I saw  "Graphic Type: POLYLINE" and I wondering Rectangle.js should change Graphic Type to POLYLINE. But what is the meaning of following line?
 TID 1500 MeasurementReport
 --TID 1501 Measurement Group
 ---Measurement Group (DCM 125007)
 ----TID 300 Measurement
https://github.com/dcmjs-org/dcmjs/blob/0e1e2921e953bde8f4707b025f584a6c558ffedd/src/utilities/TID300/index.js#L25-L35


The hint also mention about "This should be the same as a Freehand ROI, more or less." Is that mean I need to use src/adapters/Cornerstone/Freehand.js as my template for implement src/adapters/Cornerstone/Rectangle.js rather than src/adapters/Cornerstone/EllipticalRoi.js?

 
https://github.com/dcmjs-org/dcmjs/blob/0e1e2921e953bde8f4707b025f584a6c558ffedd/src/utilities/TID300/index.js#L37-L42
