### ISSUE TITLE
writeBytes using encapsulated files with lots of frames crashes the browser

### ISSUE THREAD

**Issue by dpedranti** [dcmjs-org/dcmjs#158]
Hi,

I'm doing a write() after a data.DicomMessage.readFile and Chrome will freeze up and crash if I use it on larger Dicom files with encapsulated pixel data and lots of frames.  Works great with other images that are big in size.

The file that failed is 117.3 MB with 120 frames.

The issue seems to happen in the for loop on line 258 here: https://github.com/dcmjs-org/dcmjs/blob/master/src/ValueRepresentation.js

Each iteration of that for loop becomes progressively slower until it stops somewhere in the middle of the 120 frames.

Can you help fix?

Thanks!

**Comment by dpedranti** [comment]
Sorry.  Created a duplicate of this issue by accident.

**Comment by pieper** [comment]
No worries - same thing happened to me yesterday creating issues - got 404 on submit but the issue actually had been created so it was some kind of github glitch.
