### ISSUE TITLE
DicomDict.write fails when a Sequence tag a OW type.

### ISSUE THREAD

**Issue by WoonchanCho** [dcmjs-org/dcmjs#161]
Hi,
I am recently engaged in a project that uses the dcmjs library.
This is really a great project. I am enjoying playing with this library.

I have one question about the error I am getting when writing (DicomDict.write) a new image after modifying some tags.
This error seems to happens only when there is an OW typed tag inside a SQ tag.
And the location of error is seemingly the line 247 of https://github.com/dcmjs-org/dcmjs/blob/master/src/ValueRepresentation.js.

I cannot share a dcm image the emits this error because it cannot be shared publicly.
I manually (artificially) created and attached a dcm so that you can replicate the issue.

```
const filePath = ....
const inputBuffer = fs.readFileSync(filePath);
const inputDict = DicomMessage.readFile(
    inputBuffer instanceof Uint8Array ? inputBuffer.buffer : inputBuffer,
    { ignoreErrors: true }
);

const output = inputDict.write();
```

TypeError: Cannot read property 'fragmentMultiframe' of undefined
    at OtherWordString.writeBytes (.../dcmjs/build/dcmjs.js:1333:49)
    at Tag.write (.../dcmjs/build/dcmjs.js:2542:27)
    at .../dcmjs/build/dcmjs.js:3036:25
    at Array.forEach (<anonymous>)
    at Function.write (.../dcmjs/build/dcmjs.js:3031:19)
    at SequenceOfItems.writeBytes (.../dcmjs/build/dcmjs.js:2090:36)
    at Tag.write (.../dcmjs/build/dcmjs.js:2544:27)
    at .../dcmjs/build/dcmjs.js:3036:25
    at Array.forEach (<anonymous>)
    at Function.write (.../dcmjs/build/dcmjs.js:3031:19)

Can you help this? I will also try to review and fix when I have time to look into this issue too.
Thank you so much.

[OW_IN_SQ.dcm.zip](https://github.com/dcmjs-org/dcmjs/files/5833674/OW_IN_SQ.dcm.zip)

**Comment by pieper** [comment]
It looks like this is in some code from @jmhmd - maybe you could have a look Jason?

**Comment by WoonchanCho** [comment]
Thank you so much for your comment, @pieper.
Hi @jmhmd, I think I found the cause of the issue.
The following is the brief call structure for the write method.
DicomMessage.write
    (... for all tags) Tag.write (with the writeOptions parameter)
          ValueRepresentation.writeBytes (with the writeOptions parameter)

The problem happens when the SQ type (SequenceOfItems) is handled.
SequenceOfItems recursively calls DicomMessage.write to process childrent tags "without writeOptions".
This makes writeOptions set to undefined.

I will quickly fix this and raise a PR.

Thank you.

**Comment by WoonchanCho** [comment]
I see this fix is merged into master repo. So, I will close this one.
Thank you so much.

**Comment by jmhmd** [comment]
Sorry for not chiming in earlier! Thank you for investigating and fixing @WoonchanCho

**Comment by WoonchanCho** [comment]
@jmhmd, no problem at all.
Have a great weekend.
