### ISSUE TITLE
File size keep increasing

### ISSUE THREAD

**Issue by WoonchanCho** [dcmjs-org/dcmjs#167]
Hi Team,
I keep testing this out in various ways to check if this library is in stable status and to help improve this library if any anomaly found.
I made a simple script that repetitively just reads a dicom file (DicomMessage.readFile), writes to buffer, and re-reads from the buffer written again and again to test the result at every cycle is produced constantly.

In the test with the attached file, I found that the file size grows at each cycle. The original file size was 4MB, it grew to 6MB at the first iteration, to 11MB at the next iteration, 20MB, 38MB, 74MB, 146MB and then failed with heap memory issue.

The dcm file used is one that I got from case1 at http://www.dclunie.com/pixelmedimagearchive/upmcdigitalmammotomocollection/index.html
I attached the file here too.
[dcm.zip](https://github.com/dcmjs-org/dcmjs/files/5930809/dcm.zip)

I've not looked into the source code yet, just wondered if this is a known issue?

```
dcmdump output-0.dcm |grep SOPClassUID
(0002,0002) UI =SecondaryCaptureImageStorage            #  26, 1 MediaStorageSOPClassUID
(0008,0016) UI =SecondaryCaptureImageStorage            #  26, 1 SOPClassUID`
```
The following is a script that I used for testing.
```
const fs = require('fs');
const path = require('path');
const dcmjs = require('dcmjs');
const {
  data: { DicomMessage },
} = dcmjs;

const inputPath = process.argv[2];
const outputDir = process.argv[3] || path.resolve(__dirname, 'output');
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir);
}

function iterate(inputPath) {
  let buffer = fs.readFileSync(inputPath).buffer;
  let json;

  for (let i = 0; i < 100; ++i) {
    usage();
    json = DicomMessage.readFile(buffer);
    usage();
    buffer = json.write();
    usage();
    const outputPath = path.resolve(outputDir, `output-${i}.dcm`);
    usage();
    fs.writeFileSync(outputPath, new Uint8Array(buffer));
  }
}

function usage() {
  const used = process.memoryUsage().heapUsed / 1024 / 1024;
  console.log(`${Math.round(used * 100) / 100} MB`);
}

iterate(inputPath);
```

**Comment by pieper** [comment]
Hi - thanks for testing this - it does appear there is a memory leak somewhere, and also that something extra is ending up in the file.  I suspect these are two unrelated issues.

Regarding the heap size, I guess there is some nodejs tooling we could use to see if that's transient (waiting for garbage collection or something) or a circular reference.

If the actual part 10 file is getting bigger with each round trip we should be able to track that down with something like dcmdump.  Have you looked to see what's extra after each round trip?

It would be great to look at putting a version of your script into the testing framework (which itself is in need of work).

**Comment by WoonchanCho** [comment]
Thank you so much, I will close this.
