### ISSUE TITLE
displaysegmentation example unable to parse segmentation

### ISSUE THREAD

**Issue by gangaramstyle** [dcmjs-org/dcmjs#177]
When running the [displaysegmentation example](https://dcmjs.netlify.app/displaysegmentation/) I am able to get the QIN-Headneck CT dicom to load but, when I click Get Segmentation Data, I get the error _"Uncaught TypeError: Cannot read property 'ReferencedSegmentNumber' of undefined"_

The full stack trace:
```
  | getSegmentIndex | @ | Segmentation_4X.js:903
-- | -- | -- | --
  | _loop4 | @ | Segmentation_4X.js:662
  | checkSEGsOverlapping | @ | Segmentation_4X.js:634
  | generateToolState$1 | @ | Segmentation_4X.js:355
  | generateToolState$2 | @ | Segmentation.js:65
  | parseSeg | @ | (index):129
  | (anonymous) | @ | (index):98
  | load (async) |   |  
  | getAndLoadSeg | @ | (index):97
  | onclick | @ | (index):25
```

The primary issue seems to be around this function within dcmjs/src/adapters/Cornerstone/Segmentation_4X.js:
```
const getSegmentIndex = multiframe => {
    const {
        SharedFunctionalGroupsSequence,
        PerFrameFunctionalGroupsSequence
    } = multiframe;
    return PerFrameFunctionalGroupsSequence.SegmentIdentificationSequence
        ? PerFrameFunctionalGroupsSequence.SegmentIdentificationSequence
              .ReferencedSegmentNumber
        : SharedFunctionalGroupsSequence.SegmentIdentificationSequence
              .ReferencedSegmentNumber;
};
```

The issue was specifically that the method above didn't seem to have any context on which frame was being requested and was giving an undefined because PerFrameFunctionalGroupsSequence.SegmentIdentificationSequence in the example dicom is undefined but PerFrameFunctionalGroupsSequence[frame].SegmentIdentificationSequence has the information we need. I was able to fix this issue for the dicom sample in the displaysegmentation example by modifying the method (and changing the corresponding references) to be
```
	function getSegmentIndex(multiframe, frame) {
	  var SharedFunctionalGroupsSequence = multiframe.SharedFunctionalGroupsSequence,
	      PerFrameFunctionalGroupsSequence = multiframe.PerFrameFunctionalGroupsSequence;
	  return PerFrameFunctionalGroupsSequence[frame].SegmentIdentificationSequence ? PerFrameFunctionalGroupsSequence[frame].SegmentIdentificationSequence.ReferencedSegmentNumber : SharedFunctionalGroupsSequence.SegmentIdentificationSequence.ReferencedSegmentNumber;
	}
```

Is there any reason this change works well for just the displaysegmentation example but then breaks other functionality in dcmjs that I'm not expecting?

**Comment by pieper** [comment]
Looks like this is related to this commit: https://github.com/dcmjs-org/dcmjs/commit/e4e0e7cef2cc3daeff9b203204950a70b22046c1

@igoroctaviano can you have a look?

**Comment by igoroctaviano** [comment]
> Looks like this is related to this commit: [e4e0e7c](https://github.com/dcmjs-org/dcmjs/commit/e4e0e7cef2cc3daeff9b203204950a70b22046c1)
> 
> @igoroctaviano can you have a look?

I'll take a look today, yes its related to that commit

**Comment by igoroctaviano** [comment]
@pieper https://github.com/dcmjs-org/dcmjs/pull/179 fix here.

**Comment by gangaramstyle** [comment]
I'm actually still having trouble with running the view segmentation sample with the new 0.18.1 release. The issue that I have with the new commit is that multiframe (at least the multiframe generated from the QIN-Headneck CT dicom sample) doesn't have the attribute PerFrameFunctionalGroups. 

```
    const {
        PerFrameFunctionalGroups // evaluates to undefined
        PerFrameFunctionalGroupsSequence,
        SharedFunctionalGroupsSequence
    } = multiframe;
```
As a result PerFrameFunctionalGroups as in #179 evaluates to undefined

However, modifying it to be the following works for me
```
const getSegmentIndex = (multiframe, frame) => {
    const {
        PerFrameFunctionalGroupsSequence,
        SharedFunctionalGroupsSequence
    } = multiframe;
    const PerFrameFunctionalGroups = PerFrameFunctionalGroupsSequence[frame];
    return PerFrameFunctionalGroups.SegmentIdentificationSequence
        ? PerFrameFunctionalGroups.SegmentIdentificationSequence
              .ReferencedSegmentNumber
        : PerFrameFunctionalGroupsSequence[frame].SegmentIdentificationSequence
        ? PerFrameFunctionalGroupsSequence[frame].SegmentIdentificationSequence
              .ReferencedSegmentNumber
        : SharedFunctionalGroupsSequence.SegmentIdentificationSequence
              .ReferencedSegmentNumber;
};
```

I also had errors with this sample with the checkSEGsOverlapping code. I realize that this feature isn't fully implemented yet, but would it be possible to pass the flag to skipOverlapping up one level to the generateToolState defined in Segmentation.js so that it looks like the following:

```
function generateSegmentation(
    images,
    labelmaps3DorBrushData,
    options = { includeSliceSpacing: true },
    cornerstoneToolsVersion = 4
) {
    if (cornerstoneToolsVersion === 4) {
        return Segmentation_4X.generateSegmentation(
            images,
            labelmaps3DorBrushData,
            options
        );
    }

    if (cornerstoneToolsVersion === 3) {
        return Segmentation_3X.generateSegmentation(
            images,
            labelmaps3DorBrushData,
            options
        );
    }

    console.warn(
        `No generateSegmentation adapater for cornerstone version ${cornerstoneToolsVersion}, exiting.`
    );
}
```
I created a fork with the minimal set of modifications necessary to get the example to run completely at https://github.com/gangaramstyle/dcmjs/commit/c8a5ba926ac8d61a1f3febfa79d463185e18d4cf

If it's ok I'd be happy to submit it as a PR

**Comment by igoroctaviano** [comment]
@pieper I'll create a new PR for this asap, looks like I have reintroduced the bug in the latest change. @gangaramstyle thanks for pointing it out.

**Comment by igoroctaviano** [comment]
@gangaramstyle can you open another issue / PR to cover checkSEGsOverlapping code? thank you in advance!

**Comment by igoroctaviano** [comment]
@Punzo can you take a look at gangaramstyle@c8a5ba9 commit on overlapping segs? you may have more insights on this particular fix.

**Comment by Punzo** [comment]
> @Punzo can you please take a look at [gangaramstyle/dcmjs@c8a5ba9](https://github.com/gangaramstyle/dcmjs/commit/c8a5ba9) commit on overlapping segs? you may have more insights on this particular fix.

sure!



> I'm actually still having trouble with running the view segmentation sample with the new 0.18.1 release. The issue that I have with the new commit is that multiframe (at least the multiframe generated from the QIN-Headneck CT dicom sample) doesn't have the attribute PerFrameFunctionalGroups.
> 
> ```
>     const {
>         PerFrameFunctionalGroups // evaluates to undefined
>         PerFrameFunctionalGroupsSequence,
>         SharedFunctionalGroupsSequence
>     } = multiframe;
> ```
> 
> As a result PerFrameFunctionalGroups as in #179 evaluates to undefined
> 
> However, modifying it to be the following works for me
> 
> ```
> const getSegmentIndex = (multiframe, frame) => {
>     const {
>         PerFrameFunctionalGroupsSequence,
>         SharedFunctionalGroupsSequence
>     } = multiframe;
>     const PerFrameFunctionalGroups = PerFrameFunctionalGroupsSequence[frame];
>     return PerFrameFunctionalGroups.SegmentIdentificationSequence
>         ? PerFrameFunctionalGroups.SegmentIdentificationSequence
>               .ReferencedSegmentNumber
>         : PerFrameFunctionalGroupsSequence[frame].SegmentIdentificationSequence
>         ? PerFrameFunctionalGroupsSequence[frame].SegmentIdentificationSequence
>               .ReferencedSegmentNumber
>         : SharedFunctionalGroupsSequence.SegmentIdentificationSequence
>               .ReferencedSegmentNumber;
> };
> ```
> 
> I also had errors with this sample with the checkSEGsOverlapping code. I realize that this feature isn't fully implemented yet, but would it be possible to pass the flag to skipOverlapping up one level to the generateToolState defined in Segmentation.js so that it looks like the following:
> 
> ```
> function generateToolState(
>     imageIds,
>     arrayBuffer,
>     metadataProvider,
>     skipOverlapping = false,
>     cornerstoneToolsVersion = 4
> ) {
>     if (cornerstoneToolsVersion === 4) {
>         return Segmentation_4X.generateToolState(
>             imageIds,
>             arrayBuffer,
>             metadataProvider,
>             skipOverlapping
>         );
>     }
> 
>     if (cornerstoneToolsVersion === 3) {
>         return Segmentation_3X.generateToolState(
>             imageIds,
>             arrayBuffer,
>             metadataProvider,
>             skipOverlapping
>         );
>     }
> 
>     console.warn(
>         `No generateToolState adapater for cornerstone version ${cornerstoneToolsVersion}, exiting.`
>     );
> }       options
>         );
>     }
> 
>     if (cornerstoneToolsVersion === 3) {
>         return Segmentation_3X.generateSegmentation(
>             images,
>             labelmaps3DorBrushData,
>             options
>         );
>     }
> 
>     console.warn(
>         `No generateSegmentation adapater for cornerstone version ${cornerstoneToolsVersion}, exiting.`
>     );
> }
> ```
> 
> This would allow skipping over whatever is throwing errors within the checkSEGsOverlapping code until it can be completed another time.
> 
> I created a fork with the minimal set of modifications necessary to get the example to run completely at [gangaramstyle@c8a5ba9](https://github.com/gangaramstyle/dcmjs/commit/c8a5ba926ac8d61a1f3febfa79d463185e18d4cf)
> 
> If it's ok I'd be happy to submit it as a PR

@gangaramstyle everything make sense (I just left a comment), please open a new PR. Could you also report in a new issue which were the checkSEGsOverlapping errors reported in the case of skipOverlapping = false, please?

**Comment by pieper** [comment]
Thanks everyone for the careful review and quick updates 👍 

One question:

> (at least the multiframe generated from the QIN-Headneck CT dicom sample) doesn't have the attribute PerFrameFunctionalGroups.

@gangaramstyle Can you add a pointer to the dataset?  It's not clear to me how a valid CT would not have any per-frame data unless - unless maybe it has zero or one frame maybe?  [It is 1C, so only optional if there is no per-frame data](https://dicom.innolitics.com/ciods/enhanced-ct-image/enhanced-ct-image-multi-frame-functional-groups/52009230)

**Comment by igoroctaviano** [comment]
@pieper intercepting your question to him to say that we had PerFrameFunctionalGroups attribute on our side which didn't exist, only PerFrameFunctionalGroupsSequence attribute 🤦  this is what was fixed recently

**Comment by gangaramstyle** [comment]
@pieper, the dataset in question is the one from the examples of the repo https://github.com/dcmjs-org/dcmjs/blob/master/examples/displaySegmentation/index.html#L93

I also put a PR to fix some other issues I had while trying to run the displaySegmentation example at https://github.com/dcmjs-org/dcmjs/pull/185 . Would love your review!

**Comment by gangaramstyle** [comment]
Closing this issue b/c it's successfully addressed by @igoroctaviano's commit. I'm still having an issue with https://github.com/dcmjs-org/dcmjs/issues/184
