### ISSUE TITLE
should overlay data also be encapsulated like pixel data depending on transfer syntax?

### ISSUE THREAD

**Issue by codepage949** [dcmjs-org/dcmjs#194]
[overlay-samples.zip](https://github.com/dcmjs-org/dcmjs/files/6139599/samples.zip)

i had two dicoms(one is 'Explicit VR Little Endian' of transfer syntax and other one is 'JPEG 2000 Image Compression (Lossless Only)'.

and i added overlay to each by dcmjs like below.

```js
let dcm = dcmjs.data.DicomMessage.readFile(...);

dcm.upsertTag(/*Overlay Rows Tag*/, 'US', ...);
dcm.upsertTag(/*Overlay Columns Tag*/, 'US', ...);
dcm.upsertTag(/*Overlay Type Tag*/, 'CS', ...);
dcm.upsertTag(/*Overlay Origin Tag*/, 'SS', [..., ...]);
dcm.upsertTag(/*Overlay Subtype Tag*/, 'LO', ...);

let overlay = dcmjs.data.BitArray.pack([...]);

if (overlay.length % 2) {
    const newOverlay = new Uint8Array(overlay.length + 1);

    newOverlay.set(overlay);
    newOverlay.set([0], overlay.length);

    overlay = newOverlay;
}

dcm.upsertTag(/*Overlay Data Tag*/, 'OB', [overlay.buffer]);
fs.writeFileSync(..., Buffer.from(dcm.write()));
```

as result, overlay was visible on 'Explicit VR Little Endian' dicom in weasis and aliza viewer but not on 'JPEG 2000 Image Compression (Lossless Only)'.

and i found that overlay data was encapsulated and had very different length from what i inserted on 'JPEG 2000 Image Compression (Lossless Only)' dicom.

is it correct behavior?

('JPEG 2000 Image Compression (Lossless Only)' dicom was not opened by dcmjs with error "Error: Request more than currently allocated buffer", so i checked it with dicom parser)

**Comment by pieper** [comment]
> ('JPEG 2000 Image Compression (Lossless Only)' dicom was not opened by dcmjs with error "Error: Request more than currently allocated buffer", so i checked it with dicom parser)

It sounds like this is the core issue, right?  Does this message appear before you do the overlay part or when you try to re-read the one you created?

In any case, I don't think dcmjs handles any of the encoding / decoding part of the transfer syntaxes, although issue #169 discusses adding some support for that.  So probably your overlay is being written uncompressed; perhaps you need to compress it with jpeg 2000 before inserting it?

**Comment by codepage949** [comment]
the message appear when i try to re-read the one i created.

> perhaps you need to compress it with jpeg 2000 before inserting it?

you mean i did compressing overlay data manually for jpeg2000?

no, i inserted overlay data using dcmjs without compressing but when i checked overlay data with dicom parser it is encapsulated and changed length from what i inserted.

**Comment by pieper** [comment]
> > perhaps you need to compress it with jpeg 2000 before inserting it?
> 
> you mean i did compressing overlay data manually for jpeg2000?

I have no direct experience with overlays, but I would think they need to be encoded using the same transfer syntax as other pixel data.

I'm not aware that anyone has tried to do this before with dcmjs, so your best approach might be to single step through the code and see if you can see what's going on.  A PR with tests would be welcome.  Good luck!
