### ISSUE TITLE
Error adding dicom headerError: Request more than currently allocated buffer

### ISSUE THREAD

**Issue by computurus** [dcmjs-org/dcmjs#196]
Trying to write DICOM tags into a buch of files i get the following error. Code is below:

```    dicoms.forEach((dicom) => {
        // skip files without content        
        if (dicom && dicom.content) {
            try {

            
                let DicomDict = dcmjs.data.DicomMessage.readFile(dicom.content);    

                DicomDict.dict['00100010'] = {vr: 'PN', Value: [patient.name]};
                DicomDict.dict['00100020'] = {vr: 'LO', Value: [patient.id]};
                DicomDict.dict['00100030'] = {vr: 'DA', Value: [getDicomDate(patient.birthdate)]};
                DicomDict.dict['00100040'] = {vr: 'CS', Value: [patient.sex.toUpperCase()]};    
        
                result.push({content: DicomDict.write(), filename: dicom.filename});

            }catch (e){                
                console.log("Error adding dicom header" + e)
                console.log(dicom.filename)
            }
            
        }
    });```

**Comment by pieper** [comment]
Is this async code interacting with a remote service?  Sometimes you run out of space due to a bunch of unresolved promises google for promise queue to get options.  If it's not that then please provide more context on your issue.

**Comment by computurus** [comment]
Not much else I can say. I tried different ways for writing DICOM tags. Error always the same.

**Comment by pieper** [comment]
> Not much else I can say.

Not seeing how we can help you then.  If you come up with a reproducible issue the please provide a complete example.

**Comment by computurus** [comment]
I found the error in the dcmjs files. What does it indicate?

`key: "more",
	    value: function more(length) {
	      if (this.offset + length > this.buffer.byteLength) {
	        throw new Error("Request more than currently allocated buffer");
	      }

	      var newBuf = this.buffer.slice(this.offset, this.offset + length);
	      this.increment(length);
	      return new ReadBufferStream(newBuf);
	    }`
