### ISSUE TITLE
am I missing something ?

### ISSUE THREAD

**Issue by IsmailAlaouiAbdellaoui** [dcmjs-org/dcmjs#213]
First of all, thank you very much for the fantastic work that you have been doing so far !

However, I have hard time finding a good reason why a simple dicom image viewer needs so much code and js libraries.
After all, the simple steps to display an image from a dicom file is to read the binary data, extract the image values, convert them to regular pixel values, and display them to a canvas no ?

Can you please guide me on why that much code is needed for this task (basic first example) ? I am pretty sure I am missing something like some tasks that are running in the backgroung.

Thanks !

**Comment by pieper** [comment]
I'm not sure I follow your question, since dcmjs is actually pretty thin and lightweight as far as dicom libraries go (have a look at the [dcmtk source code](https://github.com/DCMTK/dcmtk) for example).

**Comment by IsmailAlaouiAbdellaoui** [comment]
Thanks for taking the time to answer.

I was actually referring to the basic examples like the one in: https://github.com/dcmjs-org/dcmjs/blob/master/examples/display/index.html
In order to load an image, many libraries are needed ( cornerstone, its tools, utilities, hammer as well as dmjs itself ).
Therefore I was wondering what kind of processing those tools are in charge of that are not handled by dmjs.
Are all the libraries needed if I just need to display a dicom file using dcmjs ?

Thanks !

**Comment by PoyangLiu** [comment]
You can either roll all functionalities into one jumbo library and say `only one` library is needed, or you can split the functionalities into smaller libraries with more target uses.  Then `many libraries` will be needed.

I think you need to do more research yourself on these individual library do before asking why `dcmjs` doesn't handle what these libraries support.

A good starting point is https://www.npmjs.com/package/cornerstone-core

Try replacing `cornerstone-core` with `hammerjs` in the url and look for other package names and read the documentation in their github repo.

A DICOM viewer is anything but simple.  Once you read their documentation you can decide which (if any) of these libraries can be dropped in your own implementation.

**Comment by IsmailAlaouiAbdellaoui** [comment]
> You can either roll all functionalities into one jumbo library and say only one library is needed, or you can split the functionalities into smaller libraries with more target uses. Then many libraries will be needed.

Well this can be said for any code so this is not helpful.

> I think you need to do more research yourself on these individual library do before asking why dcmjs doesn't handle what these libraries support.

As a first time user, I was expecting a high level explanation on what the other libraries are used for. I guess I should not expect such explanations at this point.

> A good starting point is https://www.npmjs.com/package/cornerstone-core

I guess that's the issue. At no point in the readme (https://github.com/dcmjs-org/dcmjs) there is an explicit statement which explains that cornerstone is a pre-requisite for dcmjs to work (as well as its purpose), or that hammer is needed. Adding this would make it better for first time users to know what to expect.

Again, thanks for the time to answer, I actually found a better library with less ambiguous documentation.

**Comment by PoyangLiu** [comment]
> As a first time user, I was expecting a high level explanation on what the other libraries are used for. I guess I should not expect such explanations at this point.

Open source libraries rely on community members to contribute.  I agree that documentation is often lagging and would definitely help first time user.   Disclaimer:  I'm not a maintainer, just another community member.

> I guess that's the issue. At no point in the readme (https://github.com/dcmjs-org/dcmjs) there is an explicit statement which explains that cornerstone is a pre-requisite for dcmjs to work (as well as its purpose), or that hammer is needed. Adding this would make it better for first time users to know what to expect.

I think you have it backward.  That's because the *example* shows you how to put together a viewer.  The example requires these libraries.  'dcmjs` itself is a not a viewer. It is a DICOM utility as stated in its README.md.  `dcmjs` itself does *NOT* require these libraries.  

The dependencies of `dcmjs` is listed in its [package.json](https://github.com/dcmjs-org/dcmjs/blob/master/package.json#L50), as is the case in many libraries hosted on npm.

> Again, thanks for the time to answer, I actually found a better library with less ambiguous documentation.

Good for you.  It would be good to contribute your search with the community in case other first time users come across this post with similar confusion/frustration/need as you.

**Comment by PoyangLiu** [comment]
I have a feeling that you are looking at the wrong place.  You might want to check out https://github.com/OHIF/Viewers.  It is not a `library` though, but a fully featured viewer and makes use of `dcmjs`, `hammerjs`, `cornerstone-*` libraries.

Still not clear what you are looking for.  But perhaps you meant the [embedded mode](https://docs.ohif.org/deployment/#embedded-viewer) of that OHIF/Viewers, where everything is bundled into one package for you to include in the script tag.
