### ISSUE TITLE
Convert DICOS/DCM file to Png

### ISSUE THREAD

**Issue by james-Solutions** [dcmjs-org/dcmjs#214]
Hello,

In our Application we have been using this library, which has been helpful, to load and perform various operations on the .dcs (DICOM/DICOS etc). In the end we save our changes back as a .dcs file. However, we are wanting to convert for instance a DICOM file to a MS COCO format which requires the images/pixel data be in png format. Is there a way for this library, or another way, to convert a .dcs to a png? Also, for context, we load our .dcs pixel data into JavaScript blobs.

Thanks

**Comment by pieper** [comment]
Glad you are finding the library helpful 👍 

Yes, if you are doing this in the browser you can use [the toDataURL](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL) call on a canvas.

We don't use it in dcmjs, but [here's some example code](https://github.com/pieper/sites/blob/8a70b1489fd50187fd2d0fe2efe53ab93dba6961/glimp/growcut.html) that uses it.

There are also cross-compiled [WebAssembly codecs](https://github.com/chafey/dicom-codec-js) and you can even get all of [imagemagick](https://github.com/covictory/WASM-ImageMagick) but I suspect that the toDataURL approach will end up being a bit faster since it will use the browser's native implementation.

**Comment by hackermd** [comment]
@james-Solutions you'll have to parse the DICOM Data Set, but as @pieper pointed out you can pass individual Frame items of the Pixel Data element of a multi-frame image or the entire Pixel Data element of single-frame image to the `src` attribute of the HTML `<img>` tag. We use this approach in the [dicom-micrscopy-viewer](https://github.com/MGHComputationalPathology/dicom-microscopy-viewer) (see for example [here](https://github.com/MGHComputationalPathology/dicom-microscopy-viewer/blob/71aa48d7a56e21949bb75c24e26b6ff5eb4cb4da/src/viewer.js#L2270-L2271)).

**Comment by james-Solutions** [comment]
@hackermd and @pieper Thank you both for a good starting point. I perhaps should have mentioned we use https://github.com/cornerstonejs/cornerstone as our canvas to render the DICOS file. What I ended up doing was pulling a Uint16Array grey scale pixel data from the cornerstone canvas. https://emsis.eu/olh/HTML/topics_glossary_16bit_image.html This provides the best explanation I found for creating an RGBA format out of a 16 bit grey scale, or a luminance value. Which was namely figuring out the intervals to use to convert the 16 bit value into an 8 bit.

![16 Bit](https://emsis.eu/olh/HTML/16bitdisplay.gif)

Below is the JavaScript code for anyone interested in the future.

```
/**
 * dicosPixelDataToPng - This function takes in the cornerstone viewport element holder and the cornerstone variable
 *                       that is created in App.js. It will pull the Pixel data from cornerstone as Uint16Array in 16 Bit
 *                       grey scale value. It converts the 16 bit grey scale value into a 8 bit value (0-255). This is the
 *                       grey color produced by setting the R, G, & B Values to this one 8 bit value. This produces a Uint8ClampedArray
 *                       in RGBA format to be loaded onto a canvas element to be finally returned as a Blob of type image/png
 *
 * @param {cornerstone} cornerstone
 * @param {DOMElement} imageViewport
 * @returns {Promise} That resolves to a blob of type image/png
 */
const dicosPixelDataToPng = async (cornerstone, imageViewport) => {
    return new Promise((resolve, reject) => {
        const image = cornerstone.getImage(imageViewport);
        const pixelData = image.getPixelData();
        const EightbitPixels = new Uint8ClampedArray(
            4 * image.width * image.height
        );
        let z = 0;
        const intervals = Utils.buildIntervals();
        for (let i = 0; i < pixelData.length; i++) {
            const greyValue = Utils.findGrayValue(pixelData[i], intervals);
            EightbitPixels[z] = greyValue;
            EightbitPixels[z + 1] = greyValue;
            EightbitPixels[z + 2] = greyValue;
            EightbitPixels[z + 3] = 255;
            z += 4;
        }
        const canvas = document.createElement('canvas');
        const ctx = canvas.getContext('2d');
        ctx.canvas.width = image.width;
        ctx.canvas.height = image.height;
        const imageData = new ImageData(
            EightbitPixels,
            image.width,
            image.height
        );
        ctx.putImageData(imageData, 0, 0);
        canvas.toBlob((blob) => {
            resolve(blob);
        }, 'image/png');
    });
};
```

```
/**
     * buildIntervals - Builder function to create the needed ranges to associate a 16 bit value to an 8 bit value given certain ranges
     *
     * @returns {Array<{min: Number, max: Number}>} Array of objects with key values of min and max
     */
    static buildIntervals() {
        const intervals = [{ min: 0, max: 255 }];
        for (let i = 255; i < 65535; i += 256) {
            intervals.push({ min: i, max: i + 256 });
        }
        return intervals;
    }

    /**
     * findGrayValue - Takes in a 16 bit gray scale value between 0 - 65535 along with the build intervals from this.buildIntervals()
     *                 It returns an 8 bit gray scale value between 0 - 255. There is lose of data but the image retains most of it's quality
     *
     * @param {Number} greyScale
     * @param {Array<{min: Number, max: Number}>} intervals
     * @returns {Number} 8 Bit Color in range of 0-255
     */
    static findGrayValue(greyScale, intervals) {
        let result;
        for (let x = 0; x < intervals.length; x++) {
            if (this.inRange(greyScale, intervals[x].min, intervals[x].max)) {
                result = x;
                break;
            }
        }
        return result;
    }
```
