### ISSUE TITLE
Support using custom dictionary in DicomMetaDictionary

### ISSUE THREAD

**Issue by joy91227** [dcmjs-org/dcmjs#215]
Hello, we have some custom DICOM tags that we would like to include in our DICOM files, but because they don't exist in dictionary.js, they get dropped when we call DicomMetaDictionary.denaturalizeDataset().
I was wondering if it's possible to make DicomMetaDictionary accept a custom dictionary. 
In our own repo, we have copied and refactored DicomMetaDictionary.js to have a constructor that would accept a dictionary object in the same syntax as dictionary.js, and it worked quite well for us. 

`
export class DicomMetaDictionary {
    customDictionary: any;
    constructor(dictionary: any) {
        this.customDictionary= dictionary;
        this.nameMap = DicomMetaDictionary._generateNameMap(dictionary);
    }
}
`

Thank you for your time :)

**Comment by pieper** [comment]
That sounds like a reasonable approach to me.  Do you want to make a PR?

**Comment by joy91227** [comment]
Sure! Are there any rules that I should follow?

**Comment by pieper** [comment]
We haven't got formal policies for dcmjs, but we pretty much follow what's become normal for github these days.  You create a fork, make commits that reference this issue, make a PR, and we can discuss.  Follow existing code conventions with respect to naming, indents, etc.  From a glance the snippet you pasted looks reasonable and unlikely to break anything.

**Comment by joy91227** [comment]
#216 
Thanks! I've opened up a PR
