### ISSUE TITLE
pdf2dcm

### ISSUE THREAD

**Issue by joy91227** [dcmjs-org/dcmjs#222]
Hello, I've been looking at DCMTK, and the old version of DCMJS because I wanted to use the pdf2dcm function. I was wondering if the same conversion utilities have been implemented here already.

**Comment by pieper** [comment]
No, you'd still need the old version for that specific feature out of the box.

If you want to write some code, there are javascript libraries that should work well with the new dcmjs, like https://www.npmjs.com/package/jspdf
