### ISSUE TITLE
Export image as DICOM file 

### ISSUE THREAD

**Issue by muhammedmokbel** [dcmjs-org/dcmjs#250]
i would like to export image in dicom file and i already used some code base in dcmjs examples to help me to create dicom file in right way 

as mentioned here :  https://github.com/dcmjs-org/dcmjs/blob/add-commander/examples/nodejs/generate.js

i found code base to generate dicom file and convert this file to blob  after i set my pixeldata in dataset 

`dataset.PixelData = dataBuffer.buffer;`
`const newblob = Dcmjs.data.datasetToBlob(dataset)`
`const zip = new JSZIP()`
`zip.file('image.dcm', newblob)`
`zip.generateAsync({ type: 'blob' })
      .then(res => {
        saveAs(res, "newfile.zip", true)
        console.log(res)

      })`
      
 that's all work fine with me but when I test the zip file on microdicom the image doesn't appear 
<img width="958" alt="test" src="https://user-images.githubusercontent.com/31143764/155875928-6f97d7db-fde5-4e93-9c8b-5661aefbcddd.PNG">

**Comment by muhammedmokbel** [comment]
when I try to reconstruct dicom file and adjust bit allocated and bit stored the image become more clear but the contrast is too high 
<img width="960" alt="test3" src="https://user-images.githubusercontent.com/31143764/155882387-65196b3b-585e-4125-b6ae-9fca8bc92863.PNG">

**Comment by pieper** [comment]
Looks like you are close - maybe you just need to adjust the window center/width to match your data range.

https://github.com/dcmjs-org/dcmjs/blob/add-commander/examples/nodejs/generate.js#L83-L84

**Comment by muhammedmokbel** [comment]
@pieper thank you so much for respond
