### ISSUE TITLE
The saved image file is inconsistent with the source file.

### ISSUE THREAD

**Issue by suoc** [dcmjs-org/dcmjs#347]
http://23.94.212.216/download/dicoms/position-img.dcm

This picture has positioning lines, which disappear after reading and saving.

**Comment by pieper** [comment]
Thanks for posting this issue with a link to the data.  Perhaps someone will be able to use this to help with this.

It would help if you provided the exact code to replicate the issue, along with screenshots before and after.  If there are any diagnostic messages printed please include those too.

**Comment by suoc** [comment]
I used your nodejs sample code.
[Before](http://23.94.212.216/download/dicoms/before.png)
[After](http://23.94.212.216/download/dicoms/after.png)

**Comment by suoc** [comment]
Here si my code.
```javascript
const filePath = 'a dcm file path';

let arrayBuffer = fs.readFileSync(filePath).buffer;

let DicomDict = dcmjs.data.DicomMessage.readFile(arrayBuffer);

const dataset = dcmjs.data.DicomMetaDictionary.naturalizeDataset(DicomDict.dict);

console.log(dataset);

DicomDict.dict = dcmjs.data.DicomMetaDictionary.denaturalizeDataset(dataset);

let new_file_WriterBuffer = DicomDict.write();

fs.writeFileSync('to local path', new Buffer(new_file_WriterBuffer));
```

**Comment by suoc** [comment]
Thank you for your reply, in addition, I also found that the data parsed by dcmjs will be partially missing.
![image](http://23.94.212.216/download/dicoms/compare.png)

**Comment by suoc** [comment]
Sorry for my mistake, I found the reason and I will close this issue.

**Comment by pieper** [comment]
Okay, glad you sorted it out and thanks for looping back to report here 👍

**Comment by suoc** [comment]
The reason for this issue is that calling naturalizeDataset and then calling denaturalizeDataset will lose some tags.

**Comment by pieper** [comment]
Did you see anything odd about the data that would explain why it behaves this way?
