### ISSUE TITLE
Spacing Between Slices is equating to zero in the normalizer implementation.

### ISSUE THREAD

**Issue by JamesAPetts** [dcmjs-org/dcmjs#38]
`Spacing Between Slices` and `Slice Thickness` are equating to zero when constructing a normalized multi-frame. This is because this dot product is always equating to zero: https://github.com/dcmjs-org/dcmjs/blob/8f242379abd47f4ea1509af61023541a41f73660/src/normalizers.js#L157

I'll try to look into this next week.

**Comment by pieper** [comment]
Hi @JamesAPetts  - What input data are you using?  The line you highlighted is there to handle the case of a sheared dataset (e.g. with gantry tilt) so that the spacing between the slices is calculated by projecting back the vector between positions onto the vector perpendicular to the slice plane.  This would only be zero if the positions are in the same plane.

**Comment by fedorov** [comment]
To give the background, this came up when I installed OHIF XNAT plugin, and used it to make a segmentation of an MR series that happened to be from the PROSTATEx dataset. To the best of my knowledge, there was no shear in that dataset. When I tried to load the resulting DICOM SEG into Slicer, I got a failure, and investigating that further, I traced it down to those attributes set to 0.

**Comment by pieper** [comment]
Can you provide an example?  The logic looks right to me, but maybe there's a corner case I'm not seeing.

**Comment by fedorov** [comment]
Steve, what do you mean by "an example"? A SEG file that has those attributes set to 0 by the OHIF XNAT plugin? Or step-by-step instructions how to reproduce the problem with XNAT and XNAT OHIF plugin for a sample input MR dataset?

**Comment by pieper** [comment]
The referenced code is used to convert single frame images to multiframe, so if you have a set of single frames that result in a zero value of spacing between slices that would be "an example" of the type I'm looking for.

Of course I'm also fine with letting @JamesAPetts have a look when he has a chance.

**Comment by fedorov** [comment]
I am just a user of a "solution" that uses dcmjs (or I guess a version of it?) as one of the components. I don't have an isolated example.

**Comment by JamesAPetts** [comment]
Hey @pieper , thanks for the background on the issue. I'm a bit held up with other things until next week, but in case you wish to have a look at it before then, this seems to occur for any "single frame" series. I've confirmed the issue on multiple CT and MR datasets.

**Comment by JamesAPetts** [comment]
The issue is present on the create segmentation example on master.

**Comment by JamesAPetts** [comment]
Turns out this is just a mistake with BOTH the demo and the XNAT reader. The code is solid haha.

**Comment by JamesAPetts** [comment]
I'll fix this and push it tomorrow.

**Comment by JamesAPetts** [comment]
Done.
