### ISSUE TITLE
Can use to load dicom segment?

### ISSUE THREAD

**Issue by l5769389** [dcmjs-org/dcmjs#387]
1 . Can show me a demo to show how to load PACS server or local dicom segment file?
2. Official website example not work

**Comment by pieper** [comment]
1 - you can look at how it's done in ohif and cornerstone3d or experiment with https://portal.imaging.datacommons.cancer.gov/

2 - without free open dicomweb endpoints it's hard to keep a demo running.  Any help maintaining examples would be appreciated.
