### ISSUE TITLE
LT does not allow multiple

### ISSUE THREAD

**Issue by jssuttles** [dcmjs-org/dcmjs#46]
Add LT to singleVRs

> A character string that may contain one or more paragraphs. It may contain the Graphic Character set and the Control Characters, CR, LF, FF, and ESC. It may be padded with trailing spaces, which may be ignored, but leading spaces are considered to be significant. Data Elements with this VR shall not be multi-valued and therefore character code 5CH (the BACKSLASH "\" in ISO-IR 6) may be used.

**Comment by pieper** [comment]
Hi @jssuttles  - Just trying to understand your issue: Do you have a specific suggestion for a change?  Maybe you can share an example dataset that's not currently supported to use for testing?

**Comment by swederik** [comment]
I believe he just wants to add "LT" to this array: https://github.com/dcmjs-org/dcmjs/blob/2865d52fe0d93fc35656882d7a12cca5fdb51c7f/src/DicomMessage.js#L10

**Comment by pieper** [comment]
I have no real objection to that code change.  Would still like to have specific example if possible.

**Comment by jssuttles** [comment]
@swederik is right. Perhaps not a great use case, but I tried sticking an HL7 message into a private tag with a VR "LT". HL7 messages have backslashes. Having LT work as a multi-value VR caused the message to be broken into 2 values, which made it confusing for simple-hl7 to parse the message. I later changed this to use a "UN" VR because I don't know how long these HL7 messages will be. But as per the documentation, I just thought that you'd like to have LT conform to it.

**Comment by pieper** [comment]
Thanks for the fix! 👍
