### ISSUE TITLE
UN odd to even padding

### ISSUE THREAD

**Issue by jssuttles** [dcmjs-org/dcmjs#52]
I'm working with an older version of this, but I came across an issue that, with a cursory glance, seems to affect this version.  
http://dicom.nema.org/Dicom/2013/output/chtml/part05/sect_6.2.html  
I was rather surprised when I used this library, and it padded the UN with a null. Based on my reading of the above link, only UIs and OBs should be null padded.

**Comment by jssuttles** [comment]
I didn't realize there were so many versions of this document. Here's the latest: http://dicom.nema.org/medical/dicom/current/output/html/part05.html#sect_6.2

**Comment by jssuttles** [comment]
After reading the doc further, I think I'm mistaken. Sorry if you've read this. UN should be a length that is valid for any other VR and all other VRs are either padded to even length or have a fixed even length. I'm working on a PR to that effect.

**Comment by pieper** [comment]
Thanks for digging into this - a PR to fix anything non-standard in dcmjs will be welcome 👍

**Comment by jssuttles** [comment]
I'm actually not sure how to proceed in this case... There are some VRs that are padded with nulls and some VRs that are padded with spaces. The idea behind the UN tag is that the VR is unknown. There's no guideline in the documentation about whether to pad with spaces or nulls when it's unknown, and there's nothing that restricts it to a specific type of unknown. Ideas? Currently, I have it defaulting to null.

**Comment by malaterre** [comment]
Technically you only have one case where you can pad the odd value: when the VR is `ASCII` type (eg, typically VR:DS) but the Value Length is so big that it does not fit into the 16bits allocated Value Length. In that case DICOM standard mandates that you store VR:UN when serialized on disk (even if your app knows the actual real VR).

In all other case just pass the attribute as-is is by far the best option (your app recognize the attribute as UN means that by no means you should touch this attribute).
