### ISSUE TITLE
IntegerString (IS) and maybe other VRs should be Number not String

### ISSUE THREAD

**Issue by pieper** [dcmjs-org/dcmjs#53]
As reported by @emelalkim, IS elements are reported as quoted strings by dcmjs, but dcm4chee reports them as json Numbers.  Looking at the standard dcm4chee is correct and dcmjs should be updated.

```
dcm4chee:
"00200013": {
  "vr": "IS",
  "Value": [
    10
  ]
},
 

dcmjs
"00200013": {
      "vr": "IS",
      "Value": [
        "10"
      ]
    },
```

http://dicom.nema.org/medical/dicom/current/output/chtml/part18/sect_F.2.3.html

**Comment by fedorov** [comment]
This is kind of related to the question I wanted to ask you Steve at the last project week. Can you point me to the right place to see how you handle FL/FD? ("Single precision binary floating point number represented in IEEE 754:1985 32-bit Floating Point Number Format.") http://dicom.nema.org/medical/dicom/current/output/chtml/part05/sect_6.2.html

**Comment by pieper** [comment]
@fedorov, sure - the [vr classes](https://github.com/dcmjs-org/dcmjs/blob/2865d52fe0d93fc35656882d7a12cca5fdb51c7f/src/ValueRepresentation.js#L464-L506) read and write the [BufferStream](https://github.com/dcmjs-org/dcmjs/blob/2865d52fe0d93fc35656882d7a12cca5fdb51c7f/src/BufferStream.js#L202-L212) which uses a DataView to convert (like [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/getFloat64)).  This code was [originally contributed by Weiwei Wu](https://github.com/dcmjs-org/dcmjs/commit/9020e8d014acc3ddc9a2f28415720f78a29fdab6).

**Comment by fedorov** [comment]
Can you explain how you maintain IEEE encoding for floats going back and forth between JSON and DICOM, considering [numeric JSON format is not IEEE 754 compliant](https://stackoverflow.com/questions/43729861/how-do-i-handle-ieee-754-floating-point-numbers-in-json)?

**Comment by malaterre** [comment]
@fedorov You don't.

ref:
* https://groups.google.com/forum/#!msg/comp.protocols.dicom/-xFgvgwUckw/D59ryHXuDgAJ

**Comment by fedorov** [comment]
@malaterre yes, I also just ran into that (un-answered) post. 

So if you don't then what do you do when you do the conversion? When you get a JSON NUMBER, do you do a separate validation to determine if it can be encoded as FL/FD? How do you maintain round-trip consistency, or you also don't?

**Comment by fedorov** [comment]
I guess I am not expressing myself clearly, it can always be encoded, but I guess what I am getting at is how to deal with precision in JSON, validation of JSON wrt VRs, and loss-less round-trip.

**Comment by pieper** [comment]
It looks to us like in both IntegerString and DecimalString we need to replace
`return x`
with
`return Number(x)`

https://github.com/dcmjs-org/dcmjs/blob/f096a4190437f9b88988c94679a62c973b0547d0/src/ValueRepresentation.js#L508-L519

https://github.com/dcmjs-org/dcmjs/blob/f096a4190437f9b88988c94679a62c973b0547d0/src/ValueRepresentation.js#L441-L454

**Comment by pieper** [comment]
@fedorov regarding the open question about FL/FD can you open up a new issue if you think this is specifically something we can solve in dcmjs?  It sounds like this is actually a more general issue with the standard.

**Comment by fedorov** [comment]
@pieper I asked since I just wanted to understand how you handle this. I do not know what is the proper solution, and I do agree this is a more general issue with the standard. 

Since both dcmjs and dcmqi have to deal with this issue, I was just thinking if we could reach some consensus.

**Comment by pieper** [comment]
For reference on the original topic of strings vs numbers for various VRs this is also being addressed in the corresponding pydicom code and at some point I'd like to see a test that uses both pydicom and dcmjs to confirm interoperability and standards compliance.

https://github.com/pydicom/pydicom/pull/862

**Comment by pieper** [comment]
@cmcgee-mac can you try the changes proposed above?  If they work for OHIF SR STOW I think we should go ahead and fix anything else that needs it.

**Comment by pieper** [comment]
Regarding the FL/FD issue cited above, @fedorov please create a new issue if you think it needs to be tracked here, but from our conversations it sounds like this is just a corner case in the standard that has no good solution but hasn't been proven to cause much practical harm.

**Comment by cmcgee-mac** [comment]
@pieper I'm coming in from a specific case with the OHIF viewer. I can't easily test out changes with the dcmjs at the moment. I tried converting all "NumericValue" post-parse to Numbers and it's working well so far in the viewer.

**Comment by pieper** [comment]
Okay, sound good.  That should still work even if (when) we make the change discussed here.

**Comment by fedorov** [comment]
I just came across DICOM Supplement CP-1861 (ballot stage) related to this topic. Quoting that CP,

> The PS3.5 DICOM VR definition of DS (Decimal String) & IS (Integer String) are defined to be string representations of a numeric value (PS3.5 Table 6.2-1). However, the JSON Value Representation of the same VRs is expected to be a Number type, and not String type (PS3.18 Table F.2.3-1). 
>
> This requires the implementers to convert between a numeric value and its string representation whenever there is a need to represent DICOM data in JSON, and vice versa.
>
> However, this may cause issues of loss of precision. A String alternative is added. This is not expected to cause significant backward compatibility issues since all known JSON parsers support both Number and numbers as String.

**Comment by fedorov** [comment]
You may also want to follow the progress of "CP-1889 - Recently added OV, SV and UV VRs were not included in PS3.18 or PS3.19"

**Comment by pieper** [comment]
Related to #97 and #99.
