### ISSUE TITLE
PixelData for DICOMSEG is encoded incorrectly when frame length is not divisible by 8 for > 1 segment

### ISSUE THREAD

**Issue by JamesAPetts** [dcmjs-org/dcmjs#66]
[This issue with DCMTK](https://github.com/QIICR/dcmqi/issues/341), which now looks like it is fixed, brought to my attention that perhaps we might be doing something similar in dcmjs, as segmentation support is still rather new.

We tested on series from TCIA that usually always has at least _either_ rows or columns as a power of 2 (we did actually test on non-square images).

For DICOMSEG creation we are binarizing each segment as its added to the pixelData. If we have one segment on a stack of non-8-divisible frames we have no issue, as we bitpack the whole segment in one go. If we have multiple segments on such an image stack, there will be `image frame length % 8` voxels of unintentional packing after each segment. This will cause the pixel data to be read incorrectly after the first segment.

State of encoding for DICOMSEGs created by dcmjs:

|   | rows * columns % 8 = 0  | rows * columns % 8 != 0  |
|---|---|---|
| Single Segment  | Correct  | Correct  |
| Multiple Segments  | Correct  | Offset PixelData  |

**Comment by pieper** [comment]
Very good point - this has been on the back burner for a long time (hadn't come up in practice!)

**Comment by JamesAPetts** [comment]
> (hadn't come up in practice!)

Same here, we only discovered it when dealing with some cropped images!

We can stack all the `pixelData` in a `Unit8Array` of length `segment frames * rows * columns` as we construct it,  then bitpack the whole thing at the end and store in the seg.

**Comment by fedorov** [comment]
That is what DCMTK does, I believe. Might be a good idea to mirror organization of the DCMTK code and cross-reference it, to save effort both for you and the next person implementing this piece somewhere else. I believe this is the relevant commit with the fixes from DCMTK that should have the pointers: http://git.dcmtk.org/?p=dcmtk.git;a=commit;h=ba542273f8670f13fa222f414890849b1d1265b2.

**Comment by pieper** [comment]
We should come up with some ways to automate testing across toolkits too.

**Comment by fedorov** [comment]
@JamesAPetts in the table you put in the initial report, should it really be "segment(s)"? I think you are referring to "frame(s)".

**Comment by JamesAPetts** [comment]
It actually is segments. We currently bitpack each segment's pixelData (mulitple frames) separately, so if only have one segment things are correct be for `rows * colums % 8 !== 0` images.

**Comment by fedorov** [comment]
Ok - I asked because last time I tested this sample on some version of OHIF+dcmjs, it was not rendering correctly, but it was a while ago: https://github.com/QIICR/dcmqi/tree/master/data/segmentations/23x38x3. Did you test if this is working for you now as expected? I actually don't have a multi-segment synthetic dataset of that kind.

**Comment by JamesAPetts** [comment]
Interesting, thanks for the link. I haven't tested that dataset, but we have an example of the single-segment-being-encoded-fine in a research project at my institution (I don't I can share that data though). I'll write the fix anyways, and then I will test your data on the patched version.

**Comment by JamesAPetts** [comment]
WIP branch: #67

**Comment by JamesAPetts** [comment]
@fedorov : Tested reading your data, I think [this](https://gfycat.com/celebratedtenderhackee) is satisfactory?

**Comment by JamesAPetts** [comment]
I'll close this for now, as #67 fixes the immediate issue, but feel free to reopen if further discussion is needed.
