### ISSUE TITLE
JPEG (STR Base64) to DICOM object

### ISSUE THREAD

**Issue by vimavis** [dcmjs-org/dcmjs#76]
Hi,
Is it possible parse JPEG (STR Base64) to DICOM object ??

Thanks in advance

**Comment by pieper** [comment]
Hmm, not sure what you mean - if it's just a jpeg image then it won't have the metadata needed for a valid dicom, but you can fake it.  There's nothing in dcmjs to handle parsing jpeg or base64 strings.

**Comment by vimavis** [comment]
Thanks @pieper for your answer
