### ISSUE TITLE
Convert jpeg file ( .jpeg ) to dicom file ( .dcm )

### ISSUE THREAD

**Issue by ikhwanafath** [dcmjs-org/dcmjs#85]
Hi, how to convert jpeg file ( .jpeg ) to dicom file ( .dcm ) ? or how to create dcm file from jpeg file step by step ? thanks for reply.

**Comment by pieper** [comment]
Do you specifically need to do this in javascript?  If not, then [jpg2dcm](https://dcm4che.atlassian.net/wiki/spaces/d2/pages/1835023/jpg2dcm) executables would be easiest (or similar tools in other packages).  If you want javascript, you'll need to recreate that functionality, which shouldn't be too hard if you are comfortable with populating the headers like in the examples.

**Comment by pieper** [comment]
If you do get it working it would be great for you to post the code.

**Comment by ikhwanafath** [comment]
> Do you specifically need to do this in javascript? If not, then [jpg2dcm](https://dcm4che.atlassian.net/wiki/spaces/d2/pages/1835023/jpg2dcm) executables would be easiest (or similar tools in other packages). If you want javascript, you'll need to recreate that functionality, which shouldn't be too hard if you are comfortable with populating the headers like in the examples.

Thanks for reply, Yes, I need to do in javascript or node js like you source. But I cant found it. 
for the example in C++, 

> DicomImage img = new DicomImage();
>  // add all relevant group 28 attributes to image to tell DicomObjects how to display
>  img.DataSet.Add(Keyword.SamplesPerPixel, 1);
>  img.DataSet.Add(Keyword.PhotometricInterpretation, "MONOCHROME2");
>  img.DataSet.Add(Keyword.Rows, 512);

If I want to recreate the functionality manually, then what should I do step by step ?
May be first, I must extract pixel .jpeg data, and then I use your library for fetch pixel data convert to dicom file. 
Thanks for you suggest

**Comment by pieper** [comment]
Basically in dcmjs you just populate a javascript object with the dicom data and then write it to a buffer that will be in part10 binary format.  It's not a widely used feature at the moment so the only example is in a branch that hasn't been integrated.

https://github.com/dcmjs-org/dcmjs/blob/c93d9589868fbbe48db37309c29b5f77fe4e76da/examples/nodejs/generate.js

This just adds some dummy image data, but it should be possible to adapt everything to work with jpeg.

**Comment by ikhwanafath** [comment]
Based on your code, Am I just save as do dcm file or not ? Thanks for ur reply

**Comment by pieper** [comment]
Yes, the code I linked can be used to generate a dicom file.  But you would need to adapt it to handle jpg images.

**Comment by ikhwanafath** [comment]
> Yes, the code I linked can be used to generate a dicom file. But you would need to adapt it to handle jpg images.
Hi, thanks for reply. Sorry but I dont know how to use it. For the example, if I have **example.jpg** file form load file, when I must to use it ? 
Am I must to get the pixel image first and then convert like this ?

> pixelData = [ some pixel image data from **example.jpg**];
> pixelData.fill(100);
> dataset.PixelData = pixelData.buffer;

Am I right ? Thanks for reply..

**Comment by pieper** [comment]
I haven't done that specific task myself, but I guess you could just render the jpg by making it the src or an img tag or drawing it to a canvas and reading back the results.  Then you just need to get it in the right form to assign it as the pixel data in the dicom object.  Let us know what you work out.

**Comment by ikhwanafath** [comment]
Ok, I'll try it first. And give my result to you. Thanks

**Comment by dannyrb** [comment]
Libraries that could help with grabbing jpeg pixels: `get-pixels`, `image-pixels`, `jimp`

**Comment by pieper** [comment]
Also if you want to avoid rendering and reading back the pixels you might try [this pure js approach](https://www.npmjs.com/package/jpeg-js).

**Comment by ikhwanafath** [comment]
Hi, I tried your code. The dcm file was load. But where must I put the get pixel jpeg ? I must fill the pixeldata with pixelData.fill( [ my pixel image ]) ?

**Comment by pieper** [comment]
Sounds right. You can make a secondary capture instance with dcmtk to see
how the tags should look.

**Comment by ikhwanafath** [comment]
Hi pieper. I still confused. in my script, https://jsfiddle.net/ikhwana/vu8rq3wp/, where I must add or insert another jpeg image pixel to dcm pixel ?
Thanks.

**Comment by pieper** [comment]
Hi @ikhwanafath - sorry I don't really have much time to help debug in detail.  If you haven't already solved it, what I would suggest you try is getting an existing secondary capture image, e.g. made with one of the tools we linked to above and parse it to look at the type of the PixelData (and some of the other attributes related image size and pixel format).  Then you can see about making your pixel data match.

**Comment by ikhwanafath** [comment]
Hi pieper, Thanks for your time. 
I have found the concept, but the result was abstract picture.
this is my code

 

> const dataset = JSON.parse(jsonDataset);
>             dataset.Rows = 2000
>             dataset.Columns = 2000
> 
>             console.log('dataset.Rows ', dataset.Rows)
>             console.log('dataset.Columns ', dataset.Columns)
>             console.log('ini length argBuffer ', argBuffer.length)
> 
>             const pixelData = new Int16Array(**argBuffer**)
>             dataset.PixelData = pixelData.buffer;
>             const dicomDict = dcmjs.data.datasetToDict(dataset);
>             const buffer = Buffer.from(dicomDict.write());

argBuffer is buffer blob image, but failed . the image just retur black with white dot

**Comment by ikhwanafath** [comment]
Hi Piper,, sorry , how about my question ? Thanks btw

**Comment by pieper** [comment]
Hi - did you try my previous suggestions?

**Comment by ikhwanafath** [comment]
Hi, yes, I did. in my comment, argBuffer is the pixelData buffer.

**Comment by pieper** [comment]
I meant did you create a valid secondary capture instance using dcmtk and load it in dcmjs and try writing it back out, something like [this test](https://github.com/dcmjs-org/dcmjs/blob/master/test/test_data.js#L137-L142).  You can first confirm that secondary captures can be losslessly read and written, and then adapt your code to match the format of the data before it's written out.

**Comment by ikhwanafath** [comment]
Hi @pieper , I want it, but I need it with javascript or node js ( if can ) . First, I have get pixeldata image. So what should I do for next ? 
Just for the information, I want to convert JPEG with 1200x720 pixels.
Could you please what the next step to convert it to dicom file ?

**Comment by xuhaooo** [comment]
HI @ikhwanafath , I have the same problem as you and need to pass node.js converts ordinary pictures into DCM file. I can generate it according to your previous communication records. In fact, I can solve it DCM file problem, but I generated DCM files are opened through DICOM viewing software. You can't see clear images, but blurred pixel images. Have you solved the original problem now? Look forward to your reply!
